-- Generated by tools/build_plugins.py - do not edit by hand.
return {
    count = 17,
    bytes = 765675,
    files = {
        { path = "actions.lua", hash = "caf08fcb", size = 101176 },
        { path = "config.lua", hash = "fe036c2f", size = 16723 },
        { path = "constants.lua", hash = "b6adaebf", size = 20088 },
        { path = "draw.lua", hash = "1cff6c86", size = 14698 },
        { path = "editor.lua", hash = "ee2fbee3", size = 21419 },
        { path = "gui.lua", hash = "60c6dbc9", size = 118929 },
        { path = "header.lua", hash = "5df94ca2", size = 9265 },
        { path = "history.lua", hash = "b255850a", size = 12724 },
        { path = "main.lua", hash = "045378df", size = 39772 },
        { path = "paths.lua", hash = "1839a241", size = 36093 },
        { path = "playback.lua", hash = "ccd5f005", size = 23242 },
        { path = "recorder.lua", hash = "fc1da778", size = 12749 },
        { path = "route_mara_princess.lua", hash = "0841f3e2", size = 52848 },
        { path = "routes.lua", hash = "6043a4fb", size = 59439 },
        { path = "spellscan.lua", hash = "d17101f4", size = 28142 },
        { path = "state.lua", hash = "56b106cb", size = 17501 },
        { path = "ui.lua", hash = "b4524685", size = 180867 },
    },
}
